### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [Balancingrock/SwifterSockets#1]
Hi,
For iOS and macOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by Swiftrien** [comment]
I will look into that.

**Comment by Swiftrien** [comment]
While I can (and have) created a framework from SwifterSockets, I cannot use that framework in my main project (Swifterfire). At best I get a runtime error about the inability to find the dylib.

I could not find a solution for this. In addition Apple mentions that sharing frameworks as frameworks is not really possible, it is necessary to compile the framework by the framework user to ensure compatibility.

Hence I see little advantage in pursuing this further. It would take me too much time and there does not seem to be a payoff justifying that.
